# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='nom',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
