# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 05:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_calendar', '0002_auto_20180730_0526'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evenement_participant',
            unique_together=set([('evenement', 'participant')]),
        ),
    ]
